### ISSUE TITLE
Documentation should specify that url query param values are encoded, not decoded

### ISSUE THREAD

**Issue by heliodor** [manifoldco/grafton#59]
https://github.com/manifoldco/grafton/blob/master/specs/provider.yaml#L143-L146

Please mention that the values of the query params must be url-encoded, not decoded.

This matters for the endpoint `GET /integrations/manifold/v1/resources/<resource_id>/measures` where the `period_end` and `period_start` parameters contain colon characters that need to be url-encoded.

**Comment by seriousben** [comment]
Thanks a lot for reporting this.

We recently revamped our documentation and included your recommendation at various places like:
- https://github.com/manifoldco/grafton/blob/master/specs/provider.yaml
- https://docs.manifold.co/provider
- in our step by step guide to creating an integration: https://docs.manifold.co/docs/development-measures-2GDQGzx1TU8b0NGTNC8IEJ
