### ISSUE TITLE
Grafton returns 200 on Connector API: `v1/oauth/tokens`

### ISSUE THREAD

**Issue by mlsaito** [manifoldco/grafton#62]
Grafton returns `HTTP 200` on connector API `/v1/oauth/tokens` but the actual connector API returns `HTTP 201` as per [API specifications](https://docs.manifold.co/providers).

We used the [node-restify-sample-provider](https://github.com/manifoldco/node-restify-sample-provider) as reference and you can see on this [line](https://github.com/manifoldco/node-restify-sample-provider/blob/4a0a957fc1f8a6b59a9f368217bf61a485a1edad/index.js#L85) that it checks for `if not HTTP 200` as error handling. Grafton's connector API returns `HTTP 200` which would give a successful green check mark. However, this wouldn't work on the actual integration since connector API actually returns an `HTTP 201`.

Just a nitpick but this can save future providers some time when they encounter the same problem in the future.

**Comment by luizbranco** [comment]
Thanks @mlsaito, this should've been fixed by https://github.com/manifoldco/grafton/pull/63
